name: retro1
description: Um aplicativo para registrar 1 segundo por dia e criar timelines visuais
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Banco de dados
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.1

  # Mídia e vídeo
  image_picker: ^1.0.5
  video_player: ^2.8.1
  ffmpeg_kit_flutter_new: ^4.1.0
  image: ^4.1.3
  photo_manager: ^3.5.0
  image_cropper: ^11.0.0

  # Notificações
  flutter_local_notifications: ^19.5.0
  timezone: ^0.10.1

  # UI
  cupertino_icons: ^1.0.6
  intl: ^0.20.2
  table_calendar: ^3.0.9
  cached_network_image: ^3.3.0
  flutter_slidable: ^3.0.1

  # Utilitários
  uuid: ^4.2.1
  shared_preferences: ^2.2.2
  permission_handler: ^11.1.0
  path: ^1.8.3
  share_plus: ^7.2.1
  cross_file: ^0.3.3
  file_picker: ^8.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  hive_generator: ^2.0.1
  build_runner: ^2.4.7
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/icons/

module:
  androidX: true

flutter_launcher_icons:
  android: true
  image_path: "assets/icons/app_icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icons/app_icon.png"